//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLikeQuest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tlqEntities : DbContext
    {
        public tlqEntities()
            : base("name=tlqEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bilets> bilets { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<questions> questions { get; set; }
        public virtual DbSet<rightAnswers> rightAnswers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<wrongAnswers> wrongAnswers { get; set; }
    }
}
