//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLikeQuest
{
    using System;
    using System.Collections.Generic;
    
    public partial class rightAnswers
    {
        public int idRightAnswer { get; set; }
        public int idUser { get; set; }
        public int idQuestion { get; set; }
    
        public virtual questions questions { get; set; }
        public virtual users users { get; set; }
    }
}
